spring.application.name=fluxaj
server.port=8080

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/fluxaj?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=fluxaj
spring.datasource.password=123456789
spring.datasource.url=jdbc:mysql://localhost:3306/fluxaj

# Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Credenciales de Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# CONFIGURACIÓN DE CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fluxaj1@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Seguridad (AES Key)
config.security.secret-key= AES_SECRET_KEY=123456789
